[project]
name = "sales-api-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kornel", email = "dulkornel@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.142.2",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
sales-api-service = "sales_api_service:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]


[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]